@startuml
title Банк Стандарт Context diagram

!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(ClientNoneAuth, "Незарегистрированный клиент" )
Person(Client, "Клиент банка" )

System_Ext(SmsGateway, "СМС шлюз телеком оператора")
System_Ext(CallCentreOut, "Партнерский колл-центр")

System_Boundary(BankStandard, "Банк Стандарт") {
    System(Site, "Сайт", "Информация, заявки")

    System(InternetBank, "Интернет-банк", "Управление счетами клиента")
    SystemDb(DBMS_IB, "MS SQL", "СУБД")

    System(ABS, "Автоматизированная банковская система", "Операционные процессы")
    SystemDb(DBMS_ABS, "Oracle", "СУБД")

    System(CallCentre, "Внутренний колл-центр")
}

Rel(ClientNoneAuth, Site, "Заявки, получение информации")
Rel(Client, InternetBank, "Управление счетами")
Rel(Site, ABS, "Заявки")
Rel(InternetBank, ABS, "Управление счетами")
Rel(InternetBank, DBMS_IB, "Данные")
Rel(ABS, DBMS_ABS, "Данные")
Rel(CallCentre, ABS, "Обработка заявок, получение данных по продуктам")
Rel(CallCentreOut, ABS, "Обработка заявок, получение данных по продуктам")
Rel_Neighbor(ABS, SmsGateway, "Отправка уведомлений")
@enduml
