@startuml
title Интернет банк Container diagram

!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(Client, "Клиент банка" )
Person(ClientNoneAuth, "Незарегистрированный клиент" )

System_Ext(SmsGateway, "СМС шлюз телеком оператора")

Container_Boundary(BankStandard, "Банк Стандарт"){
    Person(FrontManger, "Менеджер фронт-офиса" )
    Person(BackManger, "Менеджер бек-офиса" )
    Container(CallCentre, "Внутренний Кол-центр", "React, Java, Postgres")

    Container(ProxyIB, "Proxy Интернет-банк", "Nodejs",  "Роутинг между монолитом и новым сервисом")
    System(Site, "Сайт", "Информация, заявки  по кредитам")

    Container(InternetBank, "Интернет-банк Монолит", ".NET Framework 4.5.", "Управление счетами клиента")
    Container(InternetBankWeb, "Интернет-банк Web", "React", "Новая веб платформа")
    SystemDb(DBMS_IB, "MS SQL", "СУБД")

    Container(ProxyService, "Proxy API Gateway", "Kong, NGINX",  "Аутентификация, роутинг, канареечные релизы")
    Container(BFF_IB_WEB, "BFF - Интернет-банк", "Java", "Агрегация данных для Интернет-банк Web")
    Container(BFF_SITE, "BFF - Сайт", "Nodejs", "Агрегация данных для Сайта")


    Container(ManagementService, "Управление АБС", "Java", "Временно, вместо шины данных")
    Container(CreditService, "Сервис кредитов", "Java", "Операции по кредитам")
    Container(SendingService, "Сервис рассылок", "Java", "Рассылка уведомлений и др. по СМС, email и др.")

    Container(ABS_Client, "Десктопный клиент АБС", "Delphi", "Управление обслуживанием депозитов")
    Container(ABS, "Автоматизированная банковская система", "Oracle", "Операционные процессы")
}

Rel(Client, ProxyIB, "API REST/Websocket, шифрование")
Rel(ClientNoneAuth, Site, "Заявки, получение информации по кредитам")

Rel(ProxyIB, InternetBank, "Операции по кредитам старые")
Rel(ProxyIB, InternetBankWeb, "Постепенный перевод по кредитам операций")

Rel(InternetBank, ProxyService, "API REST/Async")
Rel(InternetBank, DBMS_IB, "Данные")
Rel(InternetBankWeb, ProxyService, "API REST/Async")

Rel(ProxyService, BFF_IB_WEB, "API REST/Async")
Rel(Site, BFF_SITE, "Заявки, получение информации")


Rel(BFF_SITE, ManagementService, "Заявки, получение информации  по кредитам")
Rel(BFF_IB_WEB, ManagementService, "API REST/Async")

Rel_Neighbor(ManagementService, ABS, "Управление АБС")
Rel(ManagementService, CreditService, "Управление АБС")
Rel(ManagementService, SendingService, "Рассылка уведомлений")

Rel_Neighbor(CallCentre, ManagementService, "Обработка заявок")
Rel(SendingService, SmsGateway, "Рассылка по СМС")

Rel(FrontManger, ABS_Client, "Управление заявками")
Rel(BackManger, ABS_Client, "Управление счетами")

Rel(ABS_Client, ABS, "Тонкий клиент")
@enduml